### ISSUE TITLE
SPFx project created with Vue.js framework is not working

### ISSUE THREAD

**Issue by Jmsfox11** [pnp/generator-spfx#137] opened 2018-12-17 19:34 UTC
#### General Information
* [ ] Usage
* [ ] Development
* [ ] Documentation
* [ ] Feature Request
* [x] Bug

#### Specific generator
* [ ] Addons
* [ ] HandlebarsJS
* [x] Vue.js

#### What Version you are running?
* NodeJS: 10.14.2
* NPM: 6.6.0-next.0
* @pnp/spfx: 1.5.1

I recently tried creating a SPFx project with the pnp spfx generator using the Vue.js framework.  Initially when I ran gulp serve on the brand new project I recieved the error `"Cannot find module 'webpack/lib/RuleSet"`.  Once I installed webpack this error disappeared but now I get the error `"Error for resource \"PropertyControlStrings\": No localized files found under the \"lib\" directory matching pattern `\"node_modules/@pnp/spfx-property-controls/lib/loc/{locale}.js\""`  If I look in the node_modules folder I can find the correct file but the node_modules folder is not in the lib folder as the gulp seems to expect.  It seems like this is a bug.

**Comment by StfBauer** [comment] 2018-12-18 21:12
@Jmsfox11 can you please specify some more details?
What type of project have you created? Web Part / extension?
Which target platform? SP 2016, SP 2019, latest online?
Which package manager have you used?

Thank you.

**Comment by Jmsfox11** [comment] 2018-12-19 14:18
@StfBauer It is a web part project, the target platform is SP 2016, and I used npm to install the global packages, it looks like the generator uses yarn when it creates the project.  Thanks.

**Comment by StfBauer** [comment] 2018-12-19 15:04
@Jmsfox11 there is one issue according to your NodeJS version. You mentioned that you use NodeJS 10. @microsoft/generator-sharepoint and this generator currently support only NodeJS Version 8.

I will take a look if I am able to reproduce the issue on NodeJS 8.0.0 too.

**Comment by StfBauer** [comment] 2018-12-19 15:52
@Jmsfox11 Are you sure you are running on NodeJS@10? Because I got the following error message.

![screenshot 2018-12-19 at 16 49 06](https://user-images.githubusercontent.com/5503835/50230990-100d2300-03ae-11e9-89b8-d81cf65b5a43.png)

The problem seems more due using the wrong NodeJS version rather than a bug in the generator.

Please check out: [Set up your SharePoint Framework development environment](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment)
The limitations listed there applies to this generator too.

**Comment by Jmsfox11** [comment] 2018-12-19 21:40
@StfBauer  That's odd as I am pretty confident that I am using NodeJS 10 and I am not seeing that error.  But I had a coworker who has NodeJS 8 installed try creating a project and he saw the same issue, so I don't think that's causing this problem.

**Comment by StfBauer** [comment] 2018-12-19 22:34
@Jmsfox11 To reproduce your issue I tried the following settings. Does this match to yours?

<img width="956" alt="screenshot 2018-12-19 at 23 08 47" src="https://user-images.githubusercontent.com/5503835/50251312-c93a2000-03e3-11e9-89f9-1ce1ee926580.png">

Can you please show your setting too?
Can you also share a sample project I will then ```nom install``` and take a look what I end up.

I used:
* yarn@latest as the package manager

Before that I used you beta version of NPM: 6.6.0-next.0 - which also worked the same way.

In addition I created another project on Windows and again I was not able to reproduce your issue.

<img width="467" alt="screenshot 2018-12-19 at 23 30 47" src="https://user-images.githubusercontent.com/5503835/50252182-7746c980-03e6-11e9-96d3-b9f878d7ee95.png">

**Comment by Jmsfox11** [comment] 2018-12-20 17:02
@StfBauer The only difference I see is that I selected the Sharepoint 2016 option instead of SharePoint Online only for Which baseline packages do you want to target for your components.  Interestingly if I create a package with the SharePointOnline option selected then I get the expected error that I have the wrong node.js version installed.

**Comment by StfBauer** [comment] 2018-12-20 19:08
@Jmsfox11 Thank you for your reply. The thing is that we mostly need a baseline set of SPFx version 1.4.0 to create a VueJS, Angular elements project and so on.

SharePoint 2016 uses SPFx 1.1.0
SharePoint 2019 uses SPFx 1.4.0
SharePoint Online the latest version.

As you mentioned, the version check was added later than 1.1.0 in the framework. So 1.1.0 is not yet and will never be aware of that limitation.

From a testing perspective, we test SharePoint 2016, SharePoint 2019, Online from a project creation perspective. Which works but there are maybe, some issues with the NPM install and Framework packages.

Like the one you reported:
```Cannot find module 'webpack/lib/RuleSet```
```"Error for resource \"PropertyControlStrings\": No localized files found under the \"lib\"```

The first generator that officially supports this kind of extensibility we use here was SPFx 1.4.0.
Right now, because we are based on 100% on the official @microsoft/generator-sharepoint, I sadly cannot hide this option.

The only chance I have is I can list it as a limitation of pnp/spfx.

**Comment by Jmsfox11** [comment] 2018-12-20 19:35
Thanks @StfBauer  I installed the correct version of node.js and tested again and was able to confim that is the case.  A project created for SP Online works as expected while I still see the same error for SP 2016.

**Comment by StfBauer** [comment] 2018-12-30 21:31
@Jmsfox11 Do you have some questions or is it ok for you to close this issue?

**Comment by Jmsfox11** [comment] 2018-12-31 14:31
@StfBauer I don't think I have anymore questions, you can close it

**Comment by StfBauer** [comment] 2018-12-31 15:50
@Jmsfox11 Thank you very much for your support and for identifying this issue together with us.

**Closed by StfBauer** 2018-12-31 15:50 UTC
