### ISSUE TITLE
Change detection / Binding not working on Angular Element component

### ISSUE THREAD

**Issue by RayMK42** [pnp/generator-spfx#214] opened 2019-12-17 13:07 UTC
#### General Information
* [ ] Usage
* [X] Development
* [ ] Documentation
* [ ] Feature Request

#### Specific generator
* [ ] Addons
* [ ] HandlebarsJS
* [X] Angular Elements

#### What Version you are running?
* NodeJS:  10.17.0 64bit
* NPM:  6.11.3
* @pnp/spfx: 1.10.1
Note: tested with Angular CLI versions 7 and 8.

I created a very basic POC project using the @pnp/spfx generator and the Angular Elements based template.

While the project builds just fine, I am experiencing major issues with binding not working as expected inside the default created component. This is the content of my component.html file.

    <p>
       It works! Description: {{description}}
    </p>
     
    {{foo}} 
    <input type="text" [(ngModel)]="foo"/>

As you can see, I have just added a simple input to the component template, bound to a variable called "foo". The same variable is used in the interpolation above.
I would expect that when I change the value in the input field, the interpolated text changes too.

Using Chrome, the result is as expected. But when using Edge the interpolated text is not updated. Notice that this happens only when the component is tested in the workbench or the package is deployed in SharePoint. The binding / change detection works normally if I test the component **outside** SharePoint using `ng serve`.
Also worth noticing is that if I defined an initial value for the variable in the component.ts file, that value gets correctly displayed in the component, but successive changes still have no effect on the displayed interpolated value `{{foo}}`.

Checking the Edge developer toolbar doesn't seems to provide any clue.

Does anyone know if this is a known issue? I wasn't able to find any specific mentions of similar problems... but as you can understand this is somehow of a blocking issue to have.

**Comment by RayMK42** [comment] 2019-12-17 13:42
UPDATE:

I stumbled upon [this bug report ](https://github.com/angular/angular/issues/26158) in the angular repo. It is now closed, the bug should have been solved by a fix that was implemented in the `zone.js` package about a year ago.

Yet, what is interesting is that the original bug report also mentions a temporary work around: switching to an alternate ElementZoneStrategyFactory - [elements-zone-strategy](https://www.npmjs.com/package/elements-zone-strategy). Out of curiosity I tried to change my POC to use this factory and now the change detection works fine.

So, apparently, whatever the fix implemented in zone.js was... it is probably not enough for SharePoint.
Right now I will use the alternate factory while I try to gather more insight on the topic (even if I fear it may be less efficient than the default one). In the meantime, I hope this info can provide useful for other users that are experiencing the same issue.

**Comment by StfBauer** [comment] 2019-12-18 10:58
@RayMK42 would it be possible to share your POC. It would be super helpful to evaluate a possible solution. To your issue.

Thank you.

**Comment by RayMK42** [comment] 2019-12-19 10:01
Hi @StfBauer ,
Sorry for the delay. I have prepared a minimal version of the POC that just replicates the issue I mentioned. You can find it in the attached zip archive (for obvious reasons, I deleted the node_modules folders, so remember to run npm install).

Currently, if you test the web part in the SharePoint workbench using Edge, you will notice that if you change the value in the input box the nearby label (which is just the interpolated value of the same model variable the input is bound to) does not change. This does not happen if you use another browser like Chrome or if you test the web part *outside* SharePoint - for example by just running `ng serve` in the Angular project folder.

![Capture2](https://user-images.githubusercontent.com/58333624/71161541-d2a1d680-2249-11ea-9b62-7a748a9afd1a.PNG)

Now, open to the app.module.ts file.

    export class AppModule {
      constructor(private injector: Injector) {}

      ngDoBootstrap() {
        // Uncomment the following two lines and comment the third one to switch to the alternate strategy factory provided by 'elements-zone-strategy'
        //const strategyFactory = new ElementZoneStrategyFactory(HelloWorldWebPartComponent, this.injector);
        //const el = createCustomElement(HelloWorldWebPartComponent, { injector: this.injector, strategyFactory });

        const el = createCustomElement(HelloWorldWebPartComponent, { injector: this.injector });
        customElements.define('app-hello-world-web-part', el);
      }
    }

As you can see, I have already included the 'elements-zone-strategy' package I mentioned in my previous post. You only need to uncomment the two commented rows so that the web part will use the alternate strategy factory instead. At this point, if you test the web part in the SharePoint workbench the change detection works as expected even on Edge.

As I said, I don't know right now what are the difference in the way this custom packages performs zone handling, but apparently whatever they are doing  differently fixes the issue the OOTB version Angular uses by default is causing in the SharePoint+Edge scenario. This package was mentioned by user remackgeek in the Angular bug report I mentioned before (direct link to the message [here](https://github.com/angular/angular/issues/26158#issuecomment-425490741)).

Hope this info can give you some more insight on the issue. Fell free to ask for more details if I missed something you deem important.


[Poc.zip](https://github.com/pnp/generator-spfx/files/3982691/Poc.zip)

**Comment by StfBauer** [comment] 2019-12-19 14:00
@RayMK42 Thank you very much for the POC. Was great to reproduce your issue.

First, forget the element-zone-strategy this has nothing to do with it. The issue is pure Edge and not supporting custom elements, which are a result of any Angular Elements project nowadays.

As part of [web components](https://www.webcomponents.org), this was never supported and will never be supported in the current Edge browser. They are "In Development" for a long time but never landed on any Edge Browser.

This will change with Chromium Based Microsoft Edge. Finally, this browser will catch up.

The good news is you get this running even on Edge through a polyfill.

You need to install the following thing to your Angular Project:

```shell
npm install @webcomponents/custom-elements --save-dev
```

It is the polyfill for custom elements targeting Microsoft Edge.
Next, you need to change the bundling.

```
// elements-bundle.js
const concat = require('concat');

(async function build() {
  const files = [
    './node_modules/@webcomponents/custom-elements/custom-elements.min.js',
    './dist/Poc/runtime.js',
    './dist/Poc/polyfills.js',
    './dist/Poc/scripts.js',
    './dist/Poc/main.js'
  ];
  await concat(files, './dist/Poc/bundle.js');
})();
```

You will find the elements-build.js file in the root of the Angular Elements project. The only thing to add here is the reference for the custom-elements.min.js

After that simply rebuild and reload the workbench. That is basically all I had to make it work.

I guess we should add this to the Angular Elements documentation of the generator in case someone needs to support this in current state Edge too.

**Comment by RayMK42** [comment] 2019-12-19 15:30
@StfBauer Thank you for your reply and your great explanation - you are right, the issue is indeed caused by Edge incomplete support of the custom elements standards. I assumed that Edge had that covered, but I was wrong - full support is still broken. Anyway, your solution works great, so I suppose there is no need for me to include the alternate zone strategy - I will just use the polyfill you mentioned. That said, I also wonder why my other solution worked too- maybe the alternate zone strategy somehow included some polyfill? 

Out of curiosity, I also installed the "stable" version of the Chromium-based Edge browser (using the side-by-side installation method [documented here](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-update-policies#allowsxs) in case you were interested) and as expected... it just works without the need for the polyfill. There are other minor css rendering issues but nothing directly related to Angular, SharePoint or the SPFX framework.

You can safely consider this question closed now. Thanks again for the assistence.

**Comment by StfBauer** [comment] 2019-12-19 17:49
Thank you for your reply. Normally work on Mac so I have Chromium Edge installed there too but use BrowserStack to cross-browser test ;) Glad that it works for you and if you have further questions. Let us know.

**Closed by StfBauer** 2019-12-19 17:49 UTC
Labels: type: question

**Comment by dsozzi** [comment] 2020-06-01 10:50
Hi,

just a side note @StfBauer . If the web components uses Shadow DOM, if won't work even with the polyfill. Strangely it works with ie11. Only Edge (18) has this issue.
