### ISSUE TITLE
ReactJS webpart is not working "Sharepoint 2016 onwards, including 2019 and SPO"

### ISSUE THREAD

**Issue by gonadn** [pnp/generator-spfx#152] opened 2019-02-09 18:07 UTC
#### General Information
* [ ]  Usage
* [*] Development
* [ ]  Documentation
* [ ]  Feature Request

Specific generator:

* [*] ReactJS

Version:

* NodeJS: v8.15.0
* NPM: v6.7.0
* @pnp/spfx: latest 1.6.1

Iam trying to create ReactJS project/solution, afte project is created i get an error, se pic below:
![image](https://user-images.githubusercontent.com/3224441/52524473-b0404380-2c9d-11e9-8c01-fb041ee8b5c4.png)

**Comment by gonadn** [comment] 2019-02-09 18:09
after npm installing "gulp-stylelint" , i get another error:
![image](https://user-images.githubusercontent.com/3224441/52524528-2b095e80-2c9e-11e9-8892-dda5167ce468.png)

**Comment by StfBauer** [comment] 2019-02-09 19:19
What selection have you made during the project creation?

**Comment by gonadn** [comment] 2019-02-09 19:53
Step1:
![image](https://user-images.githubusercontent.com/3224441/52525596-3fecee80-2cac-11e9-9ea5-8566f8de7f90.png)

Step2:
![image](https://user-images.githubusercontent.com/3224441/52525600-52ffbe80-2cac-11e9-9af4-7889763f63f3.png)

Step3:
![image](https://user-images.githubusercontent.com/3224441/52525608-60b54400-2cac-11e9-97ea-88e4a7d5073d.png)

Step4:
![image](https://user-images.githubusercontent.com/3224441/52525614-7dea1280-2cac-11e9-9726-27b22d8e2d80.png)


Step5:
![image](https://user-images.githubusercontent.com/3224441/52525619-922e0f80-2cac-11e9-86f0-3c0abb8c7704.png)

Step6;
![image](https://user-images.githubusercontent.com/3224441/52525626-ad991a80-2cac-11e9-9bc4-2f2574231bba.png)

**Comment by StfBauer** [comment] 2019-02-09 19:57
Thank you seems like there is a problem when stylint option is not selected. It will inject the gulp task for that in the gulp file.

To fix this issue you only can remove the following section from your gulp file:
```
**
 * StyleLinter configuration
 * Reference and custom gulp task
 */
const stylelint = require('gulp-stylelint');

/* Stylelinter sub task */
let styleLintSubTask = build.subTask('stylelint', (gulp) => {

    console.log('[stylelint]: By default style lint errors will not break your build. If you want to change this behaviour, modify failAfterError parameter in gulpfile.js.');

    return gulp
        .src('src/**/*.scss')
        .pipe(stylelint({
            failAfterError: false,
            reporters: [{
                formatter: 'string',
                console: true
            }]
        }));
});

/* end sub task */

build.rig.addPreBuildTask(styleLintSubTask);
```

Will be fixed in the next version.

**Comment by gonadn** [comment] 2019-02-09 19:58
i just tried it on vm same error

**Comment by gonadn** [comment] 2019-02-09 20:24
dident work selecting stylelint, got another error:
![image](https://user-images.githubusercontent.com/3224441/52525902-20a49000-2cb1-11e9-8f81-a90430056011.png)

**Comment by gonadn** [comment] 2019-02-09 20:34
And by removing gulp lines in gulpfile.js i got this error:
![image](https://user-images.githubusercontent.com/3224441/52525984-72014f00-2cb2-11e9-9cfd-74c0e52e0a87.png)

**Comment by StfBauer** [comment] 2019-02-09 20:44
This issue is related to "[No localized files found](https://github.com/SharePoint/sp-dev-fx-controls-react/issues/39)" and is coming from the property controls. This is not caused by the generator.

**Comment by gonadn** [comment] 2019-02-09 20:48
better to just stay away from @pnp/spfx, it is just a playground of buggy solutions, nothing works....!

**Closed** 2019-02-11 11:36 UTC

**Comment by gonadn** [comment] 2019-02-11 12:36
Mister @bauer why did you close the issue, do you realy think that the issue was "No localized files found" ?
this error is just another error when creating project, and you know what STOP running from issues....
you went into trap, issue closer....

**Comment by StfBauer** [comment] 2019-02-11 16:30
Thank you very much for pointing out that it is currently possible to set up projects with unsupported dependencies. In the next release, this option will not be available anymore.
