### ISSUE TITLE
Spfx Angular Elements / @pnp/pnpjs *ngFor not working

### ISSUE THREAD

**Issue by gonadn** [pnp/generator-spfx#140] opened 2018-12-22 20:32 UTC
Spfx webpart with Angular Elements / @pnp/pnpjs not working when you try to render data dynamically.
I have tested it with static array: 
`topics: string[] = ['C','C#']`
html code:
` <ul>
      <li *ngFor="let topic of topics">{{topic}}</li>
    </ul>
  <ul>`

And with pnp:
`pnp.sp.web.lists.getByTitle(this.listName).items.get().then((items: any[]) => {
                    if (items !== null && items !== undefined) {
                        resolve(items);
                    }
                    else {
                        reject("Error")
                    }
                });`

returning 53 rows from the list.
But when i want data to be rendered, it just not rendering anything?
` <ul>
    <li *ngFor="let d of lstItems;let i=index;">
        {{d.Title}}
    </li>
  </ul>`

lstItems has 53 row in array, console.log displays all data in array, ref pic
<img width="892" alt="capturet" src="https://user-images.githubusercontent.com/3224441/50378367-f92a3300-0630-11e9-8420-054ff6370f6e.PNG">

Here is my .ts file:
`import { Component, Input, OnInit, ViewEncapsulation } from '@angular/core';
import {BaseService} from '../services/app.services';

@Component({
  selector: 'app-eika-pm-web-part',
  templateUrl: './eika-pm-web-part.component.html',
  styleUrls: ['./eika-pm-web-part.component.scss'],
  encapsulation: ViewEncapsulation.Emulated
})

export class EikaPmWebPartComponent implements OnInit {
  @Input() description: string;
  lstItems: any[] = [];
  public test: string = "Dette er test data";
  topics: string[] = ['C','C#']
  constructor(private baseSrv:BaseService) { }

  ngOnInit() {
    this._getlistData();
  }

  private _getlistData(){
    this.baseSrv.getlistData().then((data: any)=>{
      if(data!==null&&data!==undefined){
        this.lstItems = data;
      }
       console.log(this.lstItems);
    });
  }
}
`

**Comment by gonadn** [comment] 2018-12-24 13:12
Hi @StfBauer , thanks for your time, here is my sample project [Github](https://github.com/gonadn/pnpspfx).

You need to test it against SP list with columns:
export interface ISPList{
  ID: string;
  Title: string;
  Url: string;
  Bane: string;
}

Or you can just configure you own list for test.
I have 53 rows in mu list, and data is rendered in console.log.

**Comment by StfBauer** [comment] 2018-12-24 14:44
@gonadn - It seems like there are multiple issues with your code.

First thing is that you cannot compile the bundle with with following error:

<img width="640" alt="screenshot 2018-12-24 at 15 37 33" src="https://user-images.githubusercontent.com/5503835/50401851-00b51d80-0792-11e9-9766-fa9372446665.png">

With some slight modifications of your code in the pnpspfx-web-part.component.ts class:
```js

  private getlistData1() {
    var promise = new Promise((resolve, reject) => {
      this.baseSrv.getlistData1().then((data: any) => {
        if (data !== null && data !== undefined) {
          resolve(data);
        }
        else {
          reject('error')
        }
      });
    });
    return promise;
  }

  private getlistData2(): Observable<ISPList> {
    var itms;
    this.baseSrv.getlistData2().then((data) => {
      itms = data;
    });
    return itms;
  }
```
To this:

```js
  private getlistData1() {
    console.log("Get List Data 1");
    var promise = new Promise((resolve, reject) => {
      this.baseSrv.getlistData().then((data: any) => {
        if (data !== null && data !== undefined) {
          console.log(data);
          this.lstItems2 = data;
          resolve(data);
        }
        else {
          reject('error');
        }
      });
    });
    return promise;
  }

  private getlistData2(): Observable<ISPList> {
    console.log("Get List Data 2");
    var itms;
    this.baseSrv.getlistData().then((data) => {
      itms = data;
    });
    return itms;
  }
}
```

I a was able to retrieve data in the web part but it doesn't look like the lstItems2 will ever assigned to any data, which means it won't render anything unless you assign some data to the variable.

```angular
    <mat-list-item *ngFor="let d of lstItems2;" role="listitem">
       <h1>{{d.Title}}</h1>
    </mat-list-item>
```

Can you please review your code and console log the single steps. I'm sure you will be able to solve your issue.

![screenshot 2018-12-24 at 15 43 12](https://user-images.githubusercontent.com/5503835/50401946-bbddb680-0792-11e9-95fd-ce7a226ae6ed.png)

I was at least able to query the data correctly with the modifications above.

**Comment by gonadn** [comment] 2018-12-24 16:09
Oki, sorry for the bug, i had to copy paste and create new project/solution for you to test.
I have now changed / fixed the code as you explained, but i can only see static data rendered, Listitems1 and Listitems2 is not rendered.  Listitems1 and Listitems2 are assigned and in teori should get rendered/displayed on the page...

I just updated my code on GitHub

**Comment by gonadn** [comment] 2018-12-25 11:52
something is really wierd why *ngFor is not displaying dynamic data in spfx webpart. I have know tested many different ways to bind data to ngFor without any luck.  I also tested same code in a SharePoint hosted Add-Inn and it worked fine. Only difference with Add-Inn is that it use Angular-Cli and not Angular Element...

Any clue?

**Comment by gonadn** [comment] 2018-12-30 20:19
anyone?

**Comment by gonadn** [comment] 2018-12-31 15:36
Are you shure that this is a Angular Elements Bug ?
Because i have know tested in clean AE project. What i dis is i just created a new project with @pnp/spfx generator. And just deleted the -spfx project folder so that i only have clean AE project.

And for testing i am consuming data from REST Api insted of using  PnP for getting data from SharePoint.  For some reason *ngFor works as asspected with REST API. 

Here is minimal repo: [GitHub](https://github.com/gonadn/AngularElements)

**Comment by StfBauer** [comment] 2018-12-31 15:48
The only thing I am certain it is not a bug in the generator because the project was provisioned correctly and the issues are related to code. Either in SPFx or Angular Elements.
If you find clear evidence that this is a problem in SPFx please open an issue on [sp-dev-docs](https://github.com/SharePoint/sp-dev-docs).
If you find strong evidence that this is an Angular Element issue please report it to the Angular Team.

This issue list only is related to generator issues and not general development support.

Thank you for your understanding.

**Comment by gonadn** [comment] 2018-12-31 17:49
finally by digging litle more i found a better solution described in this [article](https://github.com/angular/angular/issues/26158)

Fix for this in Zone.js is not released yet, but we can use "elements-zone-strategy", witch containes bug fixes...

install the package:
`npm i --save elements-zone-strategy`

use the new strategy:
`import { ElementZoneStrategyFactory } from 'elements-zone-strategy';

const strategyFactory = new ElementZoneStrategyFactory(HelloComponent, this.injector);
const helloElement = createCustomElement(HelloComponent, { injector: this.injector, strategyFactory });
customElements.define('my-hello', helloElement);`

By adding this fix to my Angular Elements project it resolved issues with *ngFor, static and dynamic data, and issues with routing.

This is maybe not the long term fix, but will be fixed by next release from Zone.js i hope?!

**Comment by StfBauer** [comment] 2018-12-31 18:19
Thank for the update.

**Closed by StfBauer** 2018-12-31 18:19 UTC
Labels: Framework Bug, angular elements
